#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_GAME_TIMER_PERIOD 45.0E-3

#define RECT_WIDTH_OFFSET 2

#define CONFIG_QUADRANT_ONE_X DISPLAY_WIDTH/4
#define CONFIG_QUADRANT_ONE_Y DISPLAY_HEIGHT/4



#endif